services:
  app:
    container_name: saturne-dev
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    networks:
      - saturne-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres-dev
    image: postgres:latest
    env_file: .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - saturne-network

networks:
  saturne-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
