services:
  app:
    container_name: saturne-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    env_file: .env.local
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    container_name: saturne-postgres-dev
    image: postgres:15-alpine
    env_file: .env.local
    volumes:
      - saturne-postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cypress:
    profiles: [ "e2e" ]
    image: cypress/included:14.5.0
    working_dir: /e2e
    depends_on:
      - app
    env_file:
      - .env.local
    environment:
      CYPRESS_baseUrl: http://app:3000
    volumes:
      - .:/e2e
    command: [ "--headless" ]

volumes:
  saturne-postgres-data-dev:
    driver: local
