services:
  app:
    container_name: saturne-dev
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    networks:
      - saturne-network-dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres-dev
    image: postgres:15-alpine
    env_file: .env.local
    volumes:
      - saturne-postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - saturne-network-dev

networks:
  saturne-network-dev:
    driver: bridge

volumes:
  saturne-postgres-data-dev:
    driver: local
